server:
  port: 8080
  maxHttpHeaderSize: 65536
  tomcat:
    basedir:
    accesslog:
      enabled: true
      prefix: access
      pattern: '%h %t "%r" %s %b %D "%{Referer}i" "%{User-agent}i" "%{X-Requested-By}i" "%{X-B3-TraceId}i" "%{myHeader}i"'

zuul:
  routes.books.url: http://localhost:8090
  retryable: true
  ignoredServices: '*'
  SendErrorFilter:
    error:
      disable: true

ribbon:
  eureka.enabled: false

logging:
  config: classpath:logback-spring.xml